### PR TITLE
[CLEANUP] Stop using replaced PHPUnit classes

### PR DESCRIPTION
**Pull request by oliverklee**
We now use the namespaced classes in all places.

### CODE REVIEW

**Comment by JakeQZ** [comment]
Also, I wonder if we should use `ExpectationFailedException` rather than `AssertionFailedError`...?

**Comment by oliverklee** [comment]
> There are a bunch of instances in `AssertCssTest.php` that should also be accordingly changed...

I already changed those in 249d81c31dee81c987b0be5151bcadbffab36c21.

**Comment by oliverklee** [comment]
> Also, I wonder if we should use `ExpectationFailedException` rather than `AssertionFailedError`...?

Yes, that would be good. Let's do that in a follow-up PR.

**Comment by oliverklee** [comment]
Rebased to resolve the conflicts and repushed.

**Comment by JakeQZ** [comment]
> > There are a bunch of instances in `AssertCssTest.php` that should also be accordingly changed...
> 
> I already changed those in [249d81c](https://github.com/MyIntervals/emogrifier/commit/249d81c31dee81c987b0be5151bcadbffab36c21).

Yes, and I reviewed.  Some kind of dementia must be taking effect...

**Comment by oliverklee** [comment]
I have created issue #787 for using `ExpectationFailedException`.

**Pull request merged**
