### PR TITLE
[TASK] Support PHP 8.0

### LINKED ISSUE #925: Support PHP 8
Will need `composer.json` updating, and changes to the GitHub Action testing matrix.  Hopefully that will be all apart from actually making a new release.  I believe the beta/RC version can already be used with GitHub Actions.

### PR DESCRIPTION
**Pull request by JakeQZ**
Resolves #925.

### CODE REVIEW

**Comment by JakeQZ** [comment]
Blocked by #924 at present, but will hopefully enough here to give insight as to whether there is anything else we need to do or fix.

**Comment by JakeQZ** [comment]
Lint passes, at least, and the checks seem to run fine against whatever RC/beta version is currently deployed by GitHub.

**Comment by JakeQZ** [comment]
Ah, but we need to update `slevomat/coding-standard` (even though it is only used by the Sniffer against PHP 7.3, Composer requires all development dependencies to be compatible with all development tools), and this requires finding whatever replaced `SlevomatCodingStandard.TypeHints.TypeHintDeclaration`.

**Comment by JakeQZ** [comment]
That's now resolved, but the `phpunit.phar` file needs updating.  However, that won't work.  There is no version of PHPUnit compatible with both PHP 8 and PHP 7.1.  We need 7.x for PHP 7.1, but 9.x for PHP 8.  Even dropping PHP 7.1 support won't help.

I think we need to revert back to Composer for PHPUnit (i.e. revert #894), unless there's a way for Phive to handle this situation?

**Comment by oliverklee** [comment]
@JakeQZ I've tested whether Phive allows parallel installation of multiple PHPUnit versions: It doesn't. However, we could manually add a `tools/phpunit-9.4.phar` use that conditionally on the used PHP version. What do you think?

**Comment by JakeQZ** [comment]
> 
> 
> @JakeQZ I've tested whether Phive allows parallel installation of multiple PHPUnit versions: It doesn't. However, we could manually add a `tools/phpunit-9.4.phar` use that conditionally on the used PHP version. What do you think?

Can we not run `phive update phpunit` prior to running the tests, and have `<phar name="phpunit" version="^7.5 || ^9.4" installed="7.5.20" location="./tools/phpunit.phar" copy="true"/>` in `phive.xml`.  Do we even need the `.phar` files in the repository at all (other than to speed up setting up the development environment)?  Will PHIVE be installed and available to GitHub Actions or would there need to be a separate step to install it?

**Comment by JakeQZ** [comment]
Now have a green build :))

**Comment by JakeQZ** [comment]
Will make a separate PR for the changes for PHPUnit & PHIVE...

**Comment by JakeQZ** [comment]
This can be reviewed and merged now.  Note that the linked issue to be resolved is #916 not #925 (the latter which I closed as a duplicate).

**Review by oliverklee — APPROVED** [review]

**Pull request merged**
