### PR TITLE
[FEATURE] Add an ArrayIntersector class

### PR DESCRIPTION
**Pull request by JakeQZ**
Part of #708.

### CODE REVIEW

**Comment by JakeQZ** [comment]
The class is very simple, almost a one-liner.  There is a bit more to the tests, however!

**Comment by JakeQZ** [comment]
It occurs to me now that this may be not be in the best namespace - if `Pelago\Emogrifier\HtmlProcessor` is intended for, um, HTML processors, then perhaps this should be in a namespace like `Pelago\Emogrifier\Utils` or `Pelago\Emogrifier\Utilities`.  And the `Pelago\Emogrifier\CssConcatenator` class may also be better placed in such namespace.

@oliverklee, what do you think?

**Comment by oliverklee** [comment]
I was thinking about this, too. `Pelago\Emogrifier\Utilities` sounds good for both classes.

**Comment by JakeQZ** [comment]
> `Pelago\Emogrifier\Utilities` sounds good for both classes.

OK.  Added #711 for this.

**Pull request merged**
