### PR TITLE
[TASK] Make `CssInliner::setHtml` private

### PR DESCRIPTION
**Pull request by oliverklee**
This is another step towards making `CssInline` an `HtmlProcessor`.

### CODE REVIEW

**Comment by oliverklee** [comment]
> In the abstract class it is set by the constructor, so this method will ultimately be removed, I presume.

Yes, after some more refactoring.

**Comment by JakeQZ** [comment]
> Waiting to be queued

Travis seems to be stuck...

**Comment by oliverklee** [comment]
> Travis seems to be stuck...

No, it's still building. (There are quite a few builds in the queue.) You can click on the "Details" link in the checks list to see the build status.

**Comment by oliverklee** [comment]
Now everything is green.

**Pull request merged**
