### PR TITLE
[TASK] disable php-cs-fixer yoda conditions

### PR DESCRIPTION
**Pull request by SignpostMarv**
regarding: #791, https://github.com/MyIntervals/emogrifier/pull/778#discussion_r330913843

### CODE REVIEW

**Comment by SignpostMarv** [comment]
> Could we have a CHANGELOG entry ('Added' section I think)?
> 
> Thanks.

d'oh

**Comment by SignpostMarv** [comment]
*used the `--force`*

**Comment by JakeQZ** [comment]
> _used the `--force`_

That's fine in this case.  I think I should be able to uppercase the first character of the CHANGELOG title while you focus on more important work 😎

**Comment by JakeQZ** [comment]
> _used the `--force`_

And now just spotted the pun :)

**Pull request merged**
