### PR TITLE
[CLEANUP] adding & utilising composer sort-packages

### PR DESCRIPTION
**Pull request by SignpostMarv**

### CODE REVIEW

**Comment by oliverklee** [comment]
@SignpostMarv A request for future commit message (I'll update this PR's message on merging):

After the code for the type of change ([FEATURE], [BUGFIX], [CLEANUP] or [TASK]), please start the commit subject as a continuation of "This commit will …", e.g, "Add …" or "Fix …". Thanks!

**Comment by SignpostMarv** [comment]
> After the code for the type of change ([FEATURE], [BUGFIX], [CLEANUP] or [TASK]), please start the commit subject as a continuation of "This commit will …", e.g, "Add …" or "Fix …". Thanks!

* [CLEANUP] add package sorting option to composer config
* [CLEANUP] this commit re-requires a package to enact composer sort-packages

or 
* [CLEANUP] add package sorting option to composer config
* this commit re-requires a package to enact composer sort-packages

?

**Comment by oliverklee** [comment]
@SignpostMarv I don't quite understand your question. Maybe an example for a (fictional) single commit message will help:

(Subject) [BUGFIX] Warn if the HTML is empty

(Description) Previously, inlining CSS for empty HTML was possible, although this indicates that the inliner was called with broken data. Now the `CssInliner` will throw an exception, making it easier to solve the root cause of the empty HTML.

**Comment by oliverklee** [comment]
@SignpostMarv For more details, I can recommend this blog post: https://chris.beams.io/posts/git-commit/

**Comment by SignpostMarv** [comment]
> Maybe an example for a (fictional) single commit message will help:

ah; I very rarely use extended commit messages. there's a butt load of commits coming on the rebased #778 branch: 
image

will rebase these once I'm done to reword them appropriately before force-pushing.

**Comment by oliverklee** [comment]
One-liners are perfectly fine as long as there is nothing useful to add in addition to the commit message subject/heading.

**Comment by SignpostMarv** [comment]
> One-liners are perfectly fine as long as there is nothing useful to add in addition to the commit message subject/heading.

mutli-liners when resolving psalm issues may prove useful to those unfamiliar with psalm typehinting syntax.

**Comment by JakeQZ** [comment]
> ah; I very rarely use extended commit messages. there's a butt load of commits coming on the rebased #778 branch:

The title of the initial commit is potentially most important.  When squashing-and-merging, we can edit the commit message, but it will typically begin with that from the first commit.

If you encounter any issues rebasing, you might like to reference my post at https://github.com/MyIntervals/emogrifier/issues/373#issuecomment-536631092 for guidance, and possibly @oliverklee's at https://github.com/MyIntervals/emogrifier/pull/708#issuecomment-535885628 if anything goes awry.  Thanks again for contributing 🥰

**Pull request merged**
