### PR TITLE
[CLEANUP] Remove the PHPMD rule for unused private methods

### PR DESCRIPTION
**Pull request by oliverklee**
We are not using it anyway as it reports false positives.

### CODE REVIEW

**Comment by oliverklee** [comment]
Note to myself: Report this issue to the PHPMD project.

**Review by JakeQZ — APPROVED** [review]
There's an open issue (https://github.com/phpmd/phpmd/issues/502) as well as a closed one (https://github.com/phpmd/phpmd/issues/253), so you may be able to provide additional feedback without creating a new ticket.

**Comment by JakeQZ** [comment]
We should probably re-enable this once the issues have been fixed.

**Comment by oliverklee** [comment]
I have reported https://github.com/phpmd/phpmd/issues/900 for the first warning. The others are https://github.com/phpmd/phpmd/issues/897 and/or https://github.com/phpmd/phpmd/issues/502. I'm going to run Rector in order rework the callbacks.

**Comment by oliverklee** [comment]
(or maybe later …)

**Pull request merged**
