### PR TITLE
[FEATURE] Add support for PHP 7.4

### LINKED ISSUE #819: Test with PHP 7.4
We probably need to disable the platform requirements constrains for Composer for this.

### PR DESCRIPTION
**Pull request by oliverklee**
Fixes #819

### CODE REVIEW

**Comment by oliverklee** [comment]
PHP-parallel-lint issue:
https://github.com/JakubOnderka/PHP-Parallel-Lint/issues/154

PHPMD issue:
https://github.com/phpmd/phpmd/issues/658

**Comment by oliverklee** [comment]
We need a way to have the newer version of Psalm on PHP 7.4.

**Comment by oliverklee** [comment]
This PR now is ready for review.

**Comment by oliverklee** [comment]
I have just released version 3.1.0 (including support for PHP 7.4 and Symfony 5) and posted about it on social media.

**Comment by JakeQZ** [comment]
Assuming you want to prevent install on PHP 7.5 when it becomes available, until explicitly supported by Emogrifier, the `composer.json` change was incorrect.

I have found that [tilde version constraints](https://getcomposer.org/doc/articles/versions.md#tilde-version-range-) require the patch release version number to be supplied otherwise they behave like caret version constraints - i.e. `~7.4` means >=7.4 and <8.0 whereas `~7.4.0` means >=7.4 and <7.5.

**Comment by oliverklee** [comment]
Oh, I wasn't aware of this.

**Comment by JakeQZ** [comment]
Neither was I until playing around with Psalm versions earlier today for #792.

**Comment by oliverklee** [comment]
As there will be no PHP 7.5, this does not matter in this case. For the future, we know better now.

**Pull request merged**
