### PR TITLE
[TASK] Switch static analysis for the CI jobs to PHP 8.3

### PR DESCRIPTION
**Pull request by oliverklee**
This brings free performance.

### CODE REVIEW

**Comment by oliverklee** [comment]
Note: After/before this has been (force-)merged, we'll need to switch the branch protection configuration to the new jobs (as the required jobs are currently set to PHP 8.2).

**Review by JakeQZ — APPROVED** [review]
All bases covered.

**Comment by JakeQZ** [comment]
Needs some repo config change to clear out the old "expected" actions.  What is that?

**Comment by oliverklee** [comment]
> Needs some repo config change to clear out the old "expected" actions. What is that?

1. Settings > Branches > edit the `main` branch protection rule, which ends us up at https://github.com/MyIntervals/emogrifier/settings/branch_protection_rules/870902
2. remove the corresponding 8.2 rules from "Require status checks to pass before merging "
3. add the corresponding 8.3 rules there using find-as-you-type

**Pull request merged**
