### PR TITLE
[BUGFIX] Always use `DOMDocument::normalizeDocument` after loading HTML

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by JakeQZ** [comment]
> As it's recommended to use it

Do you have a citation reference for this recommendation?

**Comment by oliverklee** [comment]
> Do you have a citation reference for this recommendation?

Only the example on StackOverflow (where the recommendation is not explicit, though): https://stackoverflow.com/questions/1731531/how-to-use-phps-dom-extension-loadhtml

**Comment by oliverklee** [comment]
The more I think about it, the more I tend to remote the existing instances of `normalizeDocument` calls as this does not break anything according to our tests, and the performance argument is very alluring. @JakeQZ @zoliszabo Would that be okay for you?

Then I'd drop this PR and create the opposite PR instead.

**Comment by JakeQZ** [comment]
> @JakeQZ @zoliszabo Would that be okay for you?

I'm happy either way.

**Comment by JakeQZ** [comment]
> I'm happy either way.

Having said that, I am also persuaded by the optimization argument.  I also found [some](https://hotexamples.com/examples/-/DOMDocument/loadHTML/php-domdocument-loadhtml-method-examples.html) [examples](https://hotexamples.com/examples/-/DOMDocument/normalizeDocument/php-domdocument-normalizedocument-method-examples.html) of which about half `normalizeDocument()` after `loadHTML()` and the other half don't.

**Comment by oliverklee** [comment]
Okay then, closing in favor of the to-be-created PR that removes the `normalizeDocument` calls.

**Pull request closed without merging**
