### PR TITLE
[TASK] Deprecate enableCssToHtmlMapping

### PR DESCRIPTION
**Pull request by oliverklee**
Nowadays, we can expect email clients to understand CSS reasonably well.
So converting CSS non-CSS HTML attributes will not be needed anymore.

### CODE REVIEW

**Comment by oliverklee** [comment]
@jjriv @zoliszabo I'd like to have feedback from both of your before this gets merged.

Note: I'm thinking about creating a new class HtmlMinifier that then will provide methods for removing invisible nodes and removing class attributes (both with separate methods).

**Comment by zoliszabo** [comment]
After today's discussions about invisible node removal (https://github.com/MyIntervals/emogrifier/issues/252), class removal (https://github.com/MyIntervals/emogrifier/issues/380) and seeing this PR, I was having similar thoughts: deprecated or not to be implemented features should not be lost.

My first thought was some kind of a plug-in system, where these tangent features would be implemented as separate plugins and included/activated when needed.
Then I thought that some of these features may have sense to be used even stand-alone and the plug-in system would not make that possible. Instead, other classes with well-defined responsibilities should be worked out.

**Comment by jjriv** [comment]
I am coming to this conversation a little later but I agree with both of you. I like where this is heading. The addition of other classes seems like a good way to handle these extraneous features and focus more on the Emogrifier core.

**Comment by oliverklee** [comment]
Now that we agree on the roadmap, a review and merge would be nice. :smile:

**Pull request merged**
